version: "3.7"

services:
  lnd:
    container_name: fuse_lnd
    image: fuse/lnd:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.lnd
      args:
        LND_VERSION: "v0.14.2-beta"
    command:
      [
        "--rpclisten=0.0.0.0",
        "--restlisten=0.0.0.0",
        "--listen=0.0.0.0",
        "--nobootstrap",
        "--noseedbackup",
        "--debuglevel=info",
        "--tlsextradomain=lnd",
        "--bitcoin.active",
        "--bitcoin.regtest",
        "--bitcoin.node=bitcoind",
        "--bitcoind.rpchost=${BTC_HOST}:${BTC_RPC_PORT}",
        "--bitcoind.rpcuser=${BTC_RPC_USER}",
        "--bitcoind.rpcpass=${BTC_RPC_PASS}",
        "--bitcoind.zmqpubrawblock=${BTC_HOST}:${BTC_ZQMPUBRAWBLOCK_PORT}",
        "--bitcoind.zmqpubrawtx=${BTC_HOST}:${BTC_ZQMPUBRAWTX_PORT}",
      ]
    ports:
      - "1000:10009"
      - "1001:9735"
    restart: always
