version: "3.7"

services:
  bitcoind:
    container_name: fuse_bitcoind
    image: fuse/bitcoind:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.bitcoind
      args:
        BITCOIND_VERSION: "22.0"
    command:
      [
        "-chain=regtest",
        "-fallbackfee=0.000001",
        "-noconnect",
        "-dnsseed=0",
        "-dns=0",
        "-upnp=0",
        "-onlynet=ipv4",
        "-rpcbind=0.0.0.0:18443",
        "-rpcallowip=0.0.0.0/0",
        "-rpcuser=regtest",
        "-rpcpassword=regtest",
        "-zmqpubrawblock=tcp://0.0.0.0:12005",
        "-zmqpubrawtx=tcp://0.0.0.0:12006",
      ]
    expose:
      - "18443"
      - "12005"
      - "12006"
    ports:
      - "18443:18443"
    restart: always

  lndserver:
    container_name: fuse_lndserver
    image: fuse/lnd:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.lnd
      args:
        LND_VERSION: "v0.15.0-beta"
    command:
      [
        "--alias=lndserver",
        "--rpclisten=0.0.0.0:10009",
        "--listen=0.0.0.0",
        "--noseedbackup",
        "--debuglevel=info",
        "--bitcoin.active",
        "--bitcoin.regtest",
        "--bitcoin.node=bitcoind",
        "--bitcoind.rpchost=bitcoind:18443",
        "--bitcoind.rpcuser=regtest",
        "--bitcoind.rpcpass=regtest",
        "--bitcoind.zmqpubrawblock=bitcoind:12005",
        "--bitcoind.zmqpubrawtx=bitcoind:12006",
        "--tlsextradomain=lndserver",
      ]
    depends_on:
      - "bitcoind"
    expose:
      - "10009"
    volumes:
      - lndserver_creds:/root/.lnd

  loopserver:
    container_name: fuse_loopserver
    image: lightninglabs/loopserver:v0.9.52-beta
    restart: always
    volumes:
      - "lndserver_creds:/root/.lnd"
    depends_on:
      - lndserver
    command:
      - "daemon"
      - "--maxamt=5000000"
      - "--lnd.host=lndserver:10009"
      - "--lnd.macaroondir=/root/.lnd/data/chain/bitcoin/regtest"
      - "--lnd.tlspath=/root/.lnd/tls.cert"
    expose:
      - "11009"

  lnd:
    container_name: fuse_lnd
    image: fuse/lnd:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.lnd
      args:
        LND_VERSION: "v0.15.0-beta"
    command:
      [
        "--alias=fuse_lnd",
        "--rpclisten=0.0.0.0",
        "--restlisten=0.0.0.0",
        "--listen=0.0.0.0",
        "--nobootstrap",
        "--noseedbackup",
        "--debuglevel=info",
        "--tlsextradomain=lnd",
        "--bitcoin.active",
        "--bitcoin.regtest",
        "--bitcoin.node=bitcoind",
        "--bitcoind.rpchost=bitcoind:18443",
        "--bitcoind.rpcuser=regtest",
        "--bitcoind.rpcpass=regtest",
        "--bitcoind.zmqpubrawblock=bitcoind:12005",
        "--bitcoind.zmqpubrawtx=bitcoind:12006",
      ]
    depends_on:
      - "bitcoind"
    expose:
      - "9735"
      - "10009"
    ports:
      - "10002:10009"
    volumes:
      - lnd_creds:/root/.lnd
    restart: always

  litd:
    container_name: fuse_litd
    image: fuse/litd:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.litd
    command:
      [
        "--httpslisten=0.0.0.0:8443",
        "--uipassword=My$trongP@ssword",
        "--network=regtest",
        "--remote.lit-debuglevel=debug",
        "--remote.lnd.rpcserver=lnd:10009",
        "--remote.lnd.macaroonpath=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon",
        "--remote.lnd.tlscertpath=/root/.lnd/tls.cert",
        "--loop.loopoutmaxparts=5",
        "--loop.debuglevel=debug",
        "--loop.server.host=loopserver:11009",
        "--loop.server.notls",
        "--pool.newnodesonly",
        "--pool.insecure",
        "--pool.auctionserver=test.pool.lightning.finance:12010",
        "--faraday.min_monitored=48h",
        "--faraday.connect_bitcoin",
        "--faraday.bitcoin.host=bitcoind",
        "--faraday.bitcoin.user=regtest",
        "--faraday.bitcoin.password=regtest",
      ]
    depends_on:
      - "lnd"
    expose:
      - "8443"
    ports:
      - "10003:8443"
    volumes:
      - lnd_creds:/root/.lnd:ro
    restart: always

volumes:
  lnd_creds:
  lndserver_creds:
