version: "3.7"

services:
  bitcoind:
    container_name: fuse_bitcoind
    image: fuse/bitcoind:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.bitcoind
      args:
        BITCOIND_VERSION: "22.0"
    command:
      [
        "-chain=regtest",
        "-fallbackfee=0.000001",
        "-noconnect",
        "-dnsseed=0",
        "-dns=0",
        "-upnp=0",
        "-onlynet=ipv4",
        "-rpcbind=0.0.0.0:18443",
        "-rpcallowip=0.0.0.0/0",
        "-rpcuser=regtest",
        "-rpcpassword=regtest",
        "-zmqpubrawblock=tcp://0.0.0.0:12005",
        "-zmqpubrawtx=tcp://0.0.0.0:12006",
      ]
    expose:
      - "18443"
      - "12005"
      - "12006"
    ports:
      - "18443:18443"
    restart: always

  lnd:
    container_name: fuse_lnd
    image: fuse/lnd:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.lnd
      args:
        LND_VERSION: "v0.14.2-beta"
    command:
      [
        "--rpclisten=0.0.0.0",
        "--restlisten=0.0.0.0",
        "--listen=0.0.0.0",
        "--nobootstrap",
        "--noseedbackup",
        "--debuglevel=info",
        "--tlsextradomain=lnd",
        "--bitcoin.active",
        "--bitcoin.regtest",
        "--bitcoin.node=bitcoind",
        "--bitcoind.rpchost=bitcoind:18443",
        "--bitcoind.rpcuser=regtest",
        "--bitcoind.rpcpass=regtest",
        "--bitcoind.zmqpubrawblock=bitcoind:12005",
        "--bitcoind.zmqpubrawtx=bitcoind:12006",
      ]
    depends_on:
      - "bitcoind"
    expose:
      - "9735"
    ports:
      - "10002:10009"
    restart: always
